# Upload this Flutter project to the EXISTING repository without overwriting its Git history.
# Requires Git for Windows and write access to SHWETHA-1315/AQUACAMPUS.
# From PowerShell, run: .\PUSH_TO_GITHUB.ps1
$ErrorActionPreference = 'Stop'
$repo = 'https://github.com/SHWETHA-1315/AQUACAMPUS.git'
$targetBranch = 'main'
$work = Join-Path $env:TEMP ('aquacampus-upload-' + [guid]::NewGuid().ToString('N'))
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    throw 'Git for Windows is required: https://git-scm.com/downloads/win'
}
try {
    & git clone --branch $targetBranch $repo $work
    if ($LASTEXITCODE -ne 0) {
        throw 'Git clone failed. Check your GitHub login and repository access.'
    }
    $ignoreCopy = @('build','release','.dart_tool','.git','.idea','.vscode','android','.gradle')
    # The Android folder is generated by flutter create in CI. When building locally,
    # run flutter create --platforms=android --project-name aquacampus .
    Get-ChildItem -LiteralPath $PSScriptRoot -Force | ForEach-Object {
        if ($_.Name -notin $ignoreCopy) {
            Copy-Item -LiteralPath $_.FullName -Destination $work -Recurse -Force
        }
    }
    & git -C $work add -A
    if ($LASTEXITCODE -ne 0) { throw 'Unable to stage source files.' }
    & git -C $work diff --cached --quiet
    if ($LASTEXITCODE -eq 0) {
        Write-Host 'Already up to date. No changes to push.' -ForegroundColor Yellow
    } else {
        & git -C $work commit -m 'feat: add AQUACAMPUS Flutter campus water management app and Android APK CI'
        if ($LASTEXITCODE -ne 0) { throw 'Git commit failed. Set git config --global user.name and user.email.' }
        & git -C $work push origin $targetBranch
        if ($LASTEXITCODE -ne 0) { throw 'Git push denied. Sign in as SHWETHA-1315 with repository write permission.' }
        Write-Host 'PUSH COMPLETE' -ForegroundColor Green
    }
    Write-Host 'Open: https://github.com/SHWETHA-1315/AQUACAMPUS/actions'
    Write-Host 'After successful Android APK workflow, open the run and download AQUACAMPUS-Android-APK artifact.'
}
finally {
    if (Test-Path $work) { Remove-Item -LiteralPath $work -Recurse -Force -ErrorAction SilentlyContinue }
}
